export const wittyRemarks = [
  "I'm not a player, I just code a lot.",
  "Learning is a treasure that will follow its owner everywhere. – Chinese Proverb",
  "The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh",
  "The beautiful thing about learning is that nobody can take it away from you. – B.B. King",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "Education is the most powerful weapon which you can use to change the world. – Nelson Mandela",
  "Learning never exhausts the mind. – Leonardo da Vinci",
  "Strive for progress, not perfection.",
  "The roots of education are bitter, but the fruit is sweet. – Aristotle",
  "Don't watch the clock; do what it does. Keep going. – Sam Levenson",
  "Your work is to discover your work and then, with all your heart, to give yourself to it. – Buddha",
  "Genius is 1% inspiration, 99% perspiration. – Thomas Edison",
  "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice, and most of all, love of what you are doing or learning to do. – Pelé",
];
