export const wordsList = {
  easy: [
    { word: "apple", meaning: "リンゴ" },
    { word: "book", meaning: "本" },
    { word: "chair", meaning: "椅子" },
    { word: "desk", meaning: "机" },
    { word: "friend", meaning: "友達" },
    { word: "happy", meaning: "幸せ" },
    { word: "jump", meaning: "跳ぶ" },
    { word: "key", meaning: "鍵" },
    { word: "love", meaning: "愛" },
    { word: "orange", meaning: "オレンジ" },
    { word: "pencil", meaning: "鉛筆" },
    { word: "queen", meaning: "女王" },
    { word: "river", meaning: "川" },
    { word: "sun", meaning: "太陽" },
    { word: "tree", meaning: "木" },
    { word: "umbrella", meaning: "傘" },
    { word: "vase", meaning: "花瓶" },
    { word: "water", meaning: "水" },
    { word: "xylophone", meaning: "木琴" },
    { word: "zebra", meaning: "シマウマ" },
  ],
  medium: [
    { word: "accomplish", meaning: "達成する" },
    { word: "budget", meaning: "予算" },
    { word: "collaborate", meaning: "協力する" },
    { word: "efficient", meaning: "効率的な" },
    { word: "goal", meaning: "目標" },
    { word: "highlight", meaning: "強調する" },
    { word: "initiative", meaning: "主導権" },
    { word: "logistics", meaning: "物流" },
    { word: "negotiate", meaning: "交渉する" },
    { word: "productivity", meaning: "生産性" },
    { word: "resource", meaning: "資源" },
    { word: "strategy", meaning: "戦略" },
    { word: "transaction", meaning: "取引" },
    { word: "utilize", meaning: "活用する" },
    { word: "variable", meaning: "変数" },
    { word: "workforce", meaning: "労働力" },
    { word: "benchmark", meaning: "基準" },
    { word: "facilitate", meaning: "促進する" },
    { word: "innovate", meaning: "革新する" },
    { word: "objective", meaning: "目的" },
  ],
  hard: [
    { word: "entrepreneur", meaning: "起業家" },
    { word: "delegation", meaning: "委任" },
    { word: "philanthropy", meaning: "慈善活動" },
    { word: "consolidate", meaning: "統合する" },
    { word: "infrastructure", meaning: "基盤施設" },
    { word: "leverage", meaning: "活用する" },
    { word: "precedent", meaning: "前例" },
    { word: "proprietor", meaning: "所有者" },
    { word: "sustainability", meaning: "持続可能性" },
    { word: "synergy", meaning: "相乗効果" },
    { word: "arbitrage", meaning: "裁定取引" },
    { word: "benchmarking", meaning: "ベンチマーク" },
    { word: "conglomerate", meaning: "複合企業" },
    { word: "derivative", meaning: "金融派生商品" },
    { word: "equilibrium", meaning: "均衡" },
    { word: "liability", meaning: "負債" },
    { word: "prospectus", meaning: "目論見書" },
    { word: "recession", meaning: "景気後退" },
    { word: "subsidy", meaning: "補助金" },
    { word: "tariff", meaning: "関税" },
  ],
  advanced: [
    { word: "amortization", meaning: "償却" },
    { word: "contingency", meaning: "偶発事象" },
    { word: "dichotomy", meaning: "二分法" },
    { word: "fiduciary", meaning: "受託者の" },
    { word: "hedging", meaning: "ヘッジ" },
    { word: "liquidity", meaning: "流動性" },
    { word: "quantitative", meaning: "定量的な" },
    { word: "solvency", meaning: "支払能力" },
    { word: "volatility", meaning: "変動性" },
    { word: "yield", meaning: "利回り" },
    { word: "anomaly", meaning: "異常" },
    { word: "collateral", meaning: "担保" },
    { word: "expropriation", meaning: "収用" },
    { word: "fiduciary", meaning: "受託者の" },
    { word: "jurisdiction", meaning: "司法権" },
    { word: "macroeconomics", meaning: "マクロ経済学" },
    { word: "oligopoly", meaning: "寡占" },
    { word: "paradigm", meaning: "パラダイム" },
    { word: "quantum", meaning: "量子" },
    { word: "zoning", meaning: "区域制" },
  ],
};
